language: ruby
script: ./script/cibuild
rvm:
  - 2.4.0
sudo: false
cache: bundler
notifications:
  email: false
matrix:
  include:
    - script: bundle exec rake rubocop
      rvm: 2.4.0
git:
  depth: 10
